title Member Lifecycle
actor Member
note left of Member: New Member
Member->WHMCS: Orders Membership
WHMCS->Member: Redirect to Payment
Member->Payment: Sign-in and approve
Payment->WHMCS: Payment accepted
WHMCS->Member: Order complete
Member->WHMCS: Enter Badge RFID tag

WHMCS->SmartWaiver: ClientAdd Hook: Check for waiver (Name, email)

alt Waiver Found
    SmartWaiver->WHMCS: Add Waiver ID to Client
    WHMCS->Badge System: Activate Badge (RFID tag)
end


alt Waiver NOT found
    SmartWaiver->WHMCS: No Waiver found
    WHMCS->Member: Email Waiver to sign
    Member->SmartWaiver: Sign Waiver
    SmartWaiver->WHMCS: Waiver Filled out
    WHMCS->Badge System: Activate Badge (RFID tag)
end

note left of Member: Member Loses Badge
Member->WHMCS: Enter Badge RFID tag
WHMCS->Badge System: Deactivate old badge
WHMCS->Badge System: Activate new badge

note left of Member: Member Cancels
Member->WHMCS: Member Cancels Renewal
WHMCS->Badge System: Deactivate badge
